name: bidirectional_scroll_view
description: Plugin that provides a bidirectional scrollview.
version: 0.0.3
author: Toufik Zitouni <toufiksapps@gmail.com>
homepage: https://github.com/toufikzitouni/flutter-bidirectional_scrollview_plugin

flutter:
  plugin:
    androidPackage: com.yourcompany.bidirectionalscrollview
    pluginClass: BidirectionalScrollViewPlugin

dependencies:
  flutter:
    sdk: flutter
